### ISSUE TITLE
Update user guide with an example of the URI for the Required parameter "Host"

### ISSUE THREAD

**Issue by christopher-eiq** [eclecticiq/intelligence-center-app-qradar#18]
In the app setup/config page, the required parameter "Host" requires a URI for the EIQ IC which includes the version of the  API, in the format (as per our User Guide):

`https://<hostname>/api/<version>`

For anyone who's unaware of the new API bundled with the EIQ IC, and/or doesn't know what particular version ships with their particular version of the EIQ IC, it's unclear what URI to enter in the "Host" field.

It would be useful to:
a) Include an example in the User Guide of what the URI should look like
b) Include a screenshot  or instructions on how to determine the version of the API for the EIQ IC

**Comment by puja-sacumen** [comment]
Included an example of the hostname and version which is used currently.
