### ISSUE TITLE
Lookup function only returns one result

### ISSUE THREAD

**Issue by benjwebster** [eclecticiq/intelligence-center-app-qradar#19]
Lookup only returns one entity in the case that multiple exist.

This makes the feature unreliable and requires users to check the TIP rather than use the lookup function.

Example here with 2 entities discussing same observable, but lookup only returns a single entity every time.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/18141485/196694338-e741eee9-055a-4522-9598-f5456a1fa8b0.png">

<img width="895" alt="image" src="https://user-images.githubusercontent.com/18141485/196694500-c020c4a1-f9d5-4191-9856-781a82db45c7.png">

**Comment by puja-sacumen** [comment]
Changes done in Bugfix/documentation issues.

**Comment by himynamesdave** [comment]
fixed in 6e44b00
