### ISSUE TITLE
Documentation broken link

### ISSUE THREAD

**Issue by benjwebster** [eclecticiq/intelligence-center-app-qradar#21]
https://github.com/eclecticiq/intelligence-center-app-qradar/blob/main/docs/USER-MANUAL.md

Step 1 visits a broken link https://www.ibm.com/docs/SS42VS_7.3.2/com.ibm.qradar.doc/b_siem_inst.pdf 

<img width="706" alt="image" src="https://user-images.githubusercontent.com/18141485/196712727-c4f9a665-d6cc-4202-aa05-50dda32c0db4.png">

**Comment by puja-sacumen** [comment]
Fixed in bugfix/documentation_issues
Since 7.3.3 has reached EOL, therefore doc available for 7.4.3.
