### ISSUE TITLE
Documentation link to QRadar User Guide just points to docs homepage

### ISSUE THREAD

**Issue by benjwebster** [eclecticiq/intelligence-center-app-qradar#22]
https://github.com/eclecticiq/intelligence-center-app-qradar/blob/main/docs/USER-MANUAL.md#step-1-configure-the-outgoing-feeds-you-wish-to-use-with-the-qradar-app

The link to the "EclecticIQ Intelligence Center User Guide" just visits the docs portal homepage.

**Comment by himynamesdave** [comment]
fixed in f91578b

cc @zed-eiq
