### ISSUE TITLE
Documentation Step 1 "TODO"

### ISSUE THREAD

**Issue by benjwebster** [eclecticiq/intelligence-center-app-qradar#23]
Step 1 to actually download the application is not completed. Users must navigate to releases on github to download the app but this is not obvious.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/18141485/196713183-c88b7f9a-9393-49c2-ab26-563e7e9e4236.png">

**Comment by puja-sacumen** [comment]
Fixed in branch bugfix/documentation_issues
