### ISSUE TITLE
Documentation does not provide clear instruction on EclecticIQ Intelligence Center configuration

### ISSUE THREAD

**Issue by benjwebster** [eclecticiq/intelligence-center-app-qradar#24]
Docs on github point to docs portal homepage.

Navigating to QRadar documentation on EclecticIQ docs portal (for example: https://docs.eclecticiq.com/integrations/apps/ibm-qradar/install-and-configure-the-app-on-qradar) has banner that suggests documentation is obsolete and user should visit github documentation.

Circular dependency.

This leaves the user unsure about the required configuration for outgoing feeds in the EclecticIQ Intelligence Center.

**Comment by himynamesdave** [comment]
fixed in f91578b

cc @zed-eiq
