### ISSUE TITLE
Be able to connect using a self signed certificate

### ISSUE THREAD

**Issue by himynamesdave** [eclecticiq/intelligence-center-app-qradar#26]
The app now only lets you connect if you have a valid certificate installed on your TIP. Please make a options to also allow self signed or other wise "invalid" certificates. This used to be an checkbox in the old app. This is especially useful in a test setup.

Same change as https://github.com/eclecticiq/intelligence-center-app-splunk-ta/issues/19

**Comment by jamesoc-eiq** [comment]
Hi Folks, I just wanted to clarify that there is more than one solution here and we should be aiming for the most secure option.
They are as follows:

1. Allow the admin to manually import a CA cert or self-signed certificate (e.g. a PEM / DER file) and have it be added to the trusted-certs / CA bundle used by the App going forward. The cert can also be removed from the bundle as needed.

2. Allow the admin to enter a https:// URL for the TIP and have the App fetch the certificate to be trusted using a once-off TLS request that is manually invoked by the admin. This cert is then added to the trusted-certs / CA bundle used by the App going forward. The cert can also be removed from the bundle as needed. In theory an attacker could intercept this request, but they would only have one chance and would have to be ready for it. Bonus points for allowing the admin to inspect the new cert before saving it. This option is the best compromise between security and convenience for the user.

3. A check-box to ignore TLS warnings and trust any cert. This should ONLY be used for testing and should carry a strong warning. This is the least secure option and opens the App up to potential MITM attacks in production.

If we only support one option, I would suggest we go with option 2, allowing the admin to inspect the cert before saving it.

**Comment by puja-sacumen** [comment]
For the option 2 you mentioned. So will there be a separate URL where the certificate (.pem file ) will be kept and with certain credentials does it need to be downloaded?

**Comment by puja-sacumen** [comment]
Also can I have any such url so that I can download the cert and check for testing.

**Comment by jamesoc-eiq** [comment]
@puja-sacumen The certificate chain would be extracted directly from a TLS connection initiated by the App to the TIP server.
The hostname of the TIP server should already be configured and stored somewhere in the App.

Having the ability to manually supply a PEM cert-chain via pasted-text, URL fetch, or file-upload, would be closer to option 1.

**Comment by himynamesdave** [comment]
To confirm in the interests of transparency, we have decided to go with option 2:

https://github.com/eclecticiq/intelligence-center-app-qradar/issues/26#issuecomment-1303785501

**Comment by himynamesdave** [comment]
fixed in 6e44b00
