### ISSUE TITLE
Incorrect URL when creating sightings in connected EclecticIQ Instance

### ISSUE THREAD

**Issue by benjwebster** [eclecticiq/intelligence-center-app-qradar#27]
The URL provided by the system when creating a sighting uses an incorrect path and does not allow users to navigate correctly.

The URL should be updated to use the correct API path.

This URL should be, for example:

https://demo.eiq-platform.com/entity/268c2d67-111f-449d-ac77-f29f5fb88ba5 

rather than

https://demo.eiq-platform.com/api/beta/entities/268c2d67-111f-449d-ac77-f29f5fb88ba5

<img width="392" alt="image" src="https://user-images.githubusercontent.com/18141485/200323711-1d726f6b-3006-4f0a-9f04-e5b27dd0ead4.png">

**Comment by puja-sacumen** [comment]
To view any sighting created I think, the url should be:
https://demo-eiq-platform/api/version/entities/entity_id

if the url is:
https://demo-eiq-platform/entity/entity_id
then we will not be able to get the data of entity created.

**Comment by puja-sacumen** [comment]
![image](https://user-images.githubusercontent.com/98598340/200573138-852417eb-aa71-42de-97de-b8a1c290d7d9.png)

**Comment by puja-sacumen** [comment]
![image](https://user-images.githubusercontent.com/98598340/200573386-c4cbf96f-9292-431c-8d86-62918b4f25c8.png)

**Comment by himynamesdave** [comment]
Discussed today and will implement as described here

https://github.com/eclecticiq/intelligence-center-app-qradar/issues/27#issue-1438384615

**Comment by puja-sacumen** [comment]
Changes updated in the branch bugfix/documentation issues
