### ISSUE TITLE
Define exact type of Self Signed Certificate file format needed for Test Connection

### ISSUE THREAD

**Issue by MosurovicNikola** [eclecticiq/intelligence-center-app-qradar#35]
**Description of problem:**
In TCs for QRadar Test Connection we do not have pointed out types of Self Signed Certificate file format that we need to use (we use now this two formats .crt and .pem), 
and also it is not defined that Certificate needs to be in Chain format.

Please update documentation so that types of Self Signed Certificate file format are clear.

**Comment by himynamesdave** [comment]
out-of-date issue following release of 6e44b00
