### ISSUE TITLE
IBM Secure Coding failed

### ISSUE THREAD

**Issue by himynamesdave** [eclecticiq/intelligence-center-app-qradar#5]
From IBM team

"They have found some issues, if you have any questions please get in touch."

**Comment by puja-sacumen** [comment]
a) ADMIN capbailities added for endpoints updating the configuration setting.
b) Chart.bundle.js version is updated to 2.29.2
c) jquery.dataTables.min.js is updtaed to 1.11.3
d) json.dumps() is replaced with flask jsonify()
